import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { prisma } from './prisma.js';
import authRouter from './routes/auth.js';
import accountRouter from './routes/accounts.js';
import tradeRouter from './routes/trades.js';
import tagRouter from './routes/tags.js';
import analyticsRouter from './routes/analytics.js';
import transactionsRouter from './routes/transactions.js';
import settingsRouter from './routes/settings.js';
import strategiesRouter from './routes/strategies.js';
import csvRouter from './routes/csv.js';
import backupRouter from './routes/backup.js';
import attachmentsRouter from './routes/attachments.js';
import marketdataRouter from './routes/marketdata.js';
import path from 'path';

dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.use('/uploads', express.static(path.join(process.cwd(), 'uploads')));

app.get('/health', (_req, res) => res.json({ status: 'ok' }));
app.use('/auth', authRouter);
app.use('/accounts', accountRouter);
app.use('/trades', tradeRouter);
app.use('/tags', tagRouter);
app.use('/analytics', analyticsRouter);
app.use('/transactions', transactionsRouter);
app.use('/settings', settingsRouter);
app.use('/strategies', strategiesRouter);
app.use('/csv', csvRouter);
app.use('/backup', backupRouter);
app.use('/attachments', attachmentsRouter);
app.use('/marketdata', marketdataRouter);

const port = process.env.PORT || 4000;
app.listen(port, () => console.log(`Backend listening on ${port}`));
